# Generated by Django 4.2.2 on 2023-06-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecompany',
            name='date_left',
            field=models.DateField(blank=True, null=True),
        ),
    ]
