# Generated by Django 4.2.2 on 2023-06-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_company_employees_company_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='picture',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
