# Generated by Django 4.2.2 on 2023-06-26 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_employeecompanyvacation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecompanyvacation',
            name='employee',
        ),
        migrations.AlterField(
            model_name='employeecompanyvacation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employeecompany'),
        ),
    ]
