# Generated by Django 4.2.2 on 2023-06-26 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_employeecompanyvacation_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeecompanyvacation',
            old_name='company',
            new_name='employee_company',
        ),
    ]
