# Generated by Django 4.2.2 on 2023-06-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_employeecompanyvacation_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='picture_png',
            field=models.FileField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
